# Generated by Django 4.2.9 on 2024-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('publisher', models.CharField(max_length=255)),
                ('cover_page_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
